# Generated by Django 2.1.5 on 2021-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210815_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Обработано?'),
            preserve_default=False,
        ),
    ]
