# Generated by Django 2.1.5 on 2021-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_callback_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='degree',
            field=models.PositiveIntegerField(default=1, verbose_name='Оценка (звезд)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Лучшее', 'Лучшее'), ('Скидка', 'Скидка')], default=1, max_length=8, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callback',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Обработано?'),
        ),
    ]
