# Generated by Django 2.1.5 on 2021-08-18 11:02

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210818_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop.models.get_upload_path, verbose_name='Фото'),
        ),
    ]
