# Generated by Django 2.1.5 on 2021-08-19 16:41

import ckeditor.fields
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210818_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название/титл')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to=shop.models.get_upload_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банера',
            },
        ),
    ]
