# Generated by Django 2.1.5 on 2021-08-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_testominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='testominal',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
