# Generated by Django 2.1.5 on 2021-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
